apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: prod-ns
  labels:
    app: mongo
spec: 
  ports:
    - port: 27017
      protocol: TCP
      name: mongo
  selector:
    app: mongo
    tier: database
  clusterIP: None