apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  labels:
    app: e-commerce-app
    service: shipping
  namespace: prod-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      service: shipping
  template:
    metadata:
      labels:
        app: e-commerce-app
        service: shipping
      namespace: prod-ns
    spec:
      containers:
      - name: shipping-service
        image: ghcr.io/muhaimin-a8/shipping_service:latest
        ports:
          - containerPort: 3001
        env:
        - name: AMQP_URL
          value: amqp://$(RABBITMQ_SERVICE_HOST):5672
