apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-tier
  labels:
    app: microservices
    tier: support
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: support
  template:
    metadata: 
      labels:
        app: microservices
        tier: support
    spec:
      containers:
      - name: counter
        image: lrakai/microservices:counter-v1
        env:
          - name: API_URL
            value: http://app-tier.deployments:8080
      - name: poller
        image: lrakai/microservices:poller-v1
        env: 
          - name: API_URL
            value: http://app-tier:$(APP_TIER_SERVICE_PORT)