apiVersion: v1
kind: Service
metadata:
  name: backend-tier
  labels:
    app: karsajobs
  namespace: prod-ns
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: backend
  selector:
    tier: backend
  clusterIP: None
