apiVersion: v1
kind: Service
metadata:
  name: frontend-tier
  labels:
    app: karsajobs
  namespace: prod-ns
spec:
  ports:
  - name: http
    protocol: TCP
    targetPort: 80
  - name: https
    protocol: HTTPS
    targetPort: 443
  selector:
    tier: frontend
  type: NodePort
    
