apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: prod-ns
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
      tier: messagebroker
  serviceName: rabbitmq
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      namespace: prod-ns
      labels:
        app: rabbitmq
        tier: messagebroker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: rabbitmq:3.11-management
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        volumeMounts:
        - name: rabbitmq-persistent-storage
          mountPath: /var/lib/rabbitmq/
      volumes:
      - name: rabbitmq-persistent-storage
        persistentVolumeClaim:
          claimName: rabbitmq-pv-claim